<<<<<<< HEAD
# Generated by Django 4.1 on 2022-10-07 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 4.1 on 2022-09-25 23:37

from django.db import migrations, models
>>>>>>> 590e3063093a3e4f85b7adfda9fc913212890b1c


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 590e3063093a3e4f85b7adfda9fc913212890b1c
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('contenido', models.TextField()),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicado', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=2000)),
>>>>>>> 590e3063093a3e4f85b7adfda9fc913212890b1c
            ],
        ),
    ]
